# Generated by Django 5.2 on 2025-08-30 04:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=45, unique=True)),
                ("surname", models.CharField(max_length=45, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=45, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="Отчество"
                    ),
                ),
                ("email", models.EmailField(max_length=45)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("администратор", "администратор"),
                            ("менеджер", "менеджер"),
                            ("студент", "студент"),
                            ("преподаватель", "преподаватель"),
                        ],
                        max_length=13,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                ("id_curriculum", models.AutoField(primary_key=True, serialize=False)),
                (
                    "year_of_learning_start",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(2000)]
                    ),
                ),
                (
                    "num_of_semesters_of_study",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "type_of_higher_education",
                    models.CharField(
                        choices=[
                            ("бакалавриат", "бакалавриат"),
                            ("магистратура", "магистратура"),
                            ("специалитет", "специалитет"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный план",
                "verbose_name_plural": "Учебные планы",
                "db_table": "curriculum",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id_profile", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name_of_profile",
                    models.CharField(
                        choices=[
                            ("ИИ и анализ данных", "ИИ и анализ данных"),
                            ("Корпоративный ИС", "Корпоративный ИС"),
                            ("Кибербезопасность ЦП", "Кибербезопасность ЦП"),
                            (
                                "Игровая компьютерная индустрия",
                                "Игровая компьютерная индустрия",
                            ),
                            ("Бизнес-аналитик 1С", "Бизнес-аналитик 1С"),
                            (
                                "Цифровой дизайн и веб-разработка",
                                "Цифровой дизайн и веб-разработка",
                            ),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
                "db_table": "profile",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id_subject", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name_of_subject",
                    models.CharField(
                        choices=[
                            (
                                "Автоматизация решения ОиРЗ в КИС",
                                "Автоматизация решения ОиРЗ в КИС",
                            ),
                            ("Базы данных", "Базы данных"),
                            (
                                "Алгоритмизация, программирование",
                                "Алгоритмизация, программирование",
                            ),
                            (
                                "Высокоуровневые методы программирования",
                                "Высокоуровневые методы программирования",
                            ),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Дисциплина",
                "verbose_name_plural": "Дисциплины",
                "db_table": "subjects",
            },
        ),
        migrations.CreateModel(
            name="LearningSubject",
            fields=[
                (
                    "id_learning_subjects",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "semester_after_learning",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        db_column="id_curriculum",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="accounts.curriculum",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="id_subject",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="accounts.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изученный предмет",
                "verbose_name_plural": "Изученные предметы",
                "db_table": "learning_subjects",
            },
        ),
        migrations.AddField(
            model_name="curriculum",
            name="profile",
            field=models.ForeignKey(
                db_column="id_profile",
                on_delete=django.db.models.deletion.RESTRICT,
                to="accounts.profile",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id_review", models.AutoField(primary_key=True, serialize=False)),
                ("date_of_loading", models.DateField(auto_now_add=True)),
                (
                    "review",
                    models.CharField(
                        max_length=512,
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(512)],
                    ),
                ),
                (
                    "score_of_review",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "name_of_score",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Негативный", "Негативный"),
                            ("Нейтральный", "Нейтральный"),
                            ("Положительный", "Положительный"),
                        ],
                        max_length=13,
                        null=True,
                    ),
                ),
                (
                    "learning_subject",
                    models.ForeignKey(
                        db_column="id_learning_subjects",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="accounts.learningsubject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="id",
                        limit_choices_to={"role__in": ["студент", "менеджер"]},
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "db_table": "reviews",
            },
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id_student_group",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        db_column="id_curriculum",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="accounts.curriculum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студенческая группа",
                "verbose_name_plural": "Студенческие группы",
                "db_table": "student_group",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id_student",
                    models.OneToOneField(
                        db_column="id_student",
                        limit_choices_to={"role": "студент"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_group",
                    models.OneToOneField(
                        db_column="id_student_group",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="accounts.studentgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "db_table": "students",
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("surname", "name", "patronymic", "email"),
                name="unique_info_UNIQUE",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculum",
            constraint=models.UniqueConstraint(
                fields=(
                    "year_of_learning_start",
                    "num_of_semesters_of_study",
                    "type_of_higher_education",
                    "profile",
                ),
                name="curriculum_year_num_type_profile_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("learning_subject", "user"), name="user_subj__unique"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentgroup",
            unique_together={("id_student_group", "curriculum")},
        ),
        migrations.AddConstraint(
            model_name="learningsubject",
            constraint=models.UniqueConstraint(
                fields=("subject", "curriculum", "semester_after_learning"),
                name="curric_semes_subject_unique",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("id_student", "student_group")},
        ),
    ]
