# Generated by Django 5.2 on 2025-09-14 08:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                db_column="uploaded_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_uploaded",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Загрузил",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="score_of_review",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
    ]
