# Generated by Django 5.2 on 2025-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_review_uploaded_by_alter_review_score_of_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="name_of_score",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Негативный", "Негативный"),
                    ("Нейтральный", "Нейтральный"),
                    ("Положительный", "Положительный"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
