# Generated by Django 5.2 on 2025-09-26 12:54

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_alter_review_name_of_score'),  # последняя миграция
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'user_subj__unique'
                ) THEN
                    ALTER TABLE accounts_review
                    ADD CONSTRAINT user_subj__unique
                    UNIQUE (user_id, learning_subject_id);
                END IF;
            END $$;
            """
        )
    ]
